version: "~> 1.0"
language: node_js
node_js:
- 8.16.2
before_script:
- npm install
script:
- npm run build
notifications:
  slack:
    on_failure: always
    on_pull_requests: true
    on_success: always
    rooms:
      secure: ZVU8bK0DU+JHmw1C3jbxX2aNLV6tfbYkiJSVnSQi3QK+h8vjUSUYVtN1xpGQ2RWlC0Djl6Pzf0vZUte0KSRhTFzBN/CrAVcpEP28WlvfShBsHO/1xqomm3fu75KGzsKPJ8roUYZRJBGVp/An4vS3Jkl5UcrM8SFq7Ldr9Qc4+wOBO9irg7zeyciFJsMBPZR+i/2+Jr8xhCRloUdi1T3gpzYgOIgtYDr7Elqe0nhA/jdGYkymgWxjEH0KRjjcY64MhVVzglFLME6eHd+jNcBJMUienp1sA43nMm1aby3DIM+Ysw4IejERtLWkbKKrRS5g2lGTGBN4Eiq1U5rLv3+trCsov2thl76CDXrR7XueCcRSTI9Od6ozxXx/dsfBeHgOHxwILVX2rZKmZNsogiTDWdNyb0T7t6X52RoMlphjkss3Xd2/Y5Etj/xR3BRcNXq7cRYk1digLYwtlfQGCMwMpgnOCShiixZyCujNQ7GU19IK6wFF7pGwFiYE/gnL1TPKt3OapD86SX58Iz0aqwwBNizfwhU9dlg+5kIjYI9FKF8/d+CCITSzImMKiktBvllR/QMroPPD7bTpaJ8Gf7GmrQMCEcQt6tS1fdq90dQqhCijyX2uxDv50hZMTBV9mKfu5cb5wNkTSc4hfG5PKO0Xepb5LI97z3CMLeM4maH6cWM=
